const characters = [
  {
    id: 1,
    name: 'Luke Skywalker',
    height: '172',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
  },
  {
    id: 2,
    name: 'C-3PO',
    height: '167',
    eye_color: 'yellow',
    birth_year: '112BBY',
    gender: 'n/a',
  },
  {
    id: 3,
    name: 'R2-D2',
    height: '96',
    eye_color: 'red',
    birth_year: '33BBY',
    gender: 'n/a',
  },
  {
    id: 4,
    name: 'Darth Vader',
    height: '202',
    eye_color: 'yellow',
    birth_year: '41.9BBY',
    gender: 'male',
  },
  {
    id: 5,
    name: 'Leia Organa',
    height: '150',
    eye_color: 'brown',
    birth_year: '19BBY',
    gender: 'female',
  },
  {
    id: 6,
    name: 'Owen Lars',
    height: '178',
    eye_color: 'blue',
    birth_year: '52BBY',
    gender: 'male',
  },
  {
    id: 7,
    name: 'Beru Whitesun lars',
    height: '165',
    eye_color: 'blue',
    birth_year: '47BBY',
    gender: 'female',
  },
  {
    id: 8,
    name: 'R5-D4',
    height: '97',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'n/a',
  },
  {
    id: 9,
    name: 'Biggs Darklighter',
    height: '183',
    eye_color: 'brown',
    birth_year: '24BBY',
    gender: 'male',
  },
  {
    id: 10,
    name: 'Obi-Wan Kenobi',
    height: '182',
    eye_color: 'blue-gray',
    birth_year: '57BBY',
    gender: 'male',
  },
  {
    id: 11,
    name: 'Anakin Skywalker',
    height: '188',
    eye_color: 'blue',
    birth_year: '41.9BBY',
    gender: 'male',
  },
  {
    id: 12,
    name: 'Wilhuff Tarkin',
    height: '180',
    eye_color: 'blue',
    birth_year: '64BBY',
    gender: 'male',
  },
  {
    id: 13,
    name: 'Chewbacca',
    height: '228',
    eye_color: 'blue',
    birth_year: '200BBY',
    gender: 'male',
  },
  {
    id: 14,
    name: 'Han Solo',
    height: '180',
    eye_color: 'brown',
    birth_year: '29BBY',
    gender: 'male',
  },
  {
    id: 15,
    name: 'Greedo',
    height: '173',
    eye_color: 'black',
    birth_year: '44BBY',
    gender: 'male',
  },
  {
    id: 16,
    name: 'Jabba Desilijic Tiure',
    height: '175',
    eye_color: 'orange',
    birth_year: '600BBY',
    gender: 'hermaphrodite',
  },
  {
    id: 17,
    name: 'Wedge Antilles',
    height: '170',
    eye_color: 'hazel',
    birth_year: '21BBY',
    gender: 'male',
  },
  {
    id: 18,
    name: 'Jek Tono Porkins',
    height: '180',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
  },
  {
    id: 19,
    name: 'Yoda',
    height: '66',
    eye_color: 'brown',
    birth_year: '896BBY',
    gender: 'male',
  },
  {
    id: 20,
    name: 'Palpatine',
    height: '170',
    eye_color: 'yellow',
    birth_year: '82BBY',
    gender: 'male',
  },
];

module.exports = characters;
